name: Build and Deploy Apps

on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build-app.yml
  
  deploy-ios:
    runs-on: macos-latest

    steps:
      - name: 'Upload app to TestFlight'
        uses: apple-actions/upload-testflight-build@v1
        with: 
          app-path: 'ios/App/build/App.ipa' 
          issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
          api-key-id: ${{ secrets.APPSTORE_KEY_ID }}
          api-private-key: ${{ secrets.APPSTORE_PRIVATE_KEY }}

  deploy-android:
    runs-on: ubuntu-latest

    steps:
      # Upload AAB to Google Play
      - name: Upload to Google Play
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_CREDS }}
          packageName: "com.oakcityshredfest.app"
          releaseFiles: android/app/build/outputs/bundle/release/app-release.aab
          track: internal
          status: draft
