name: Bump App Version for App Store

on:
  workflow_dispatch:
    inputs:
      next_version:
        description: 'Next version to release (e.g. 1.2.3)'
        required: true
        type: string

jobs:
  bump-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_GITHUB }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Bump app version
        run: npx capacitor-set-version -v ${{ github.event.inputs.next_version }} -b 1

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PAT_GITHUB }}
          branch: bump-version-${{ github.event.inputs.next_version }}
          base: main
          title: "Release: Bump app version to ${{ github.event.inputs.next_version }}"
          body: "This PR bumps the app version to ${{ github.event.inputs.next_version }} for the next App Store release."
          commit-message: "chore: bump app version to ${{ github.event.inputs.next_version }} for App Store"
          delete-branch: true
